version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking
    ports:
      - "5433:5432"

  # This is completely optional, but it's a good idea to have a GUI to manage the database
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@banking.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  banking_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # change this if you are not a mac user: 
      # https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach
      DATABASE_URL: "postgresql://postgres:postgres@host.docker.internal:5433/banking"
    image: banking_api:latest
